# Generated by Django 3.2 on 2021-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('Cases', models.FloatField(blank=True, default=0, null=True)),
                ('Deaths', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'Covid',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.TextField(blank=True, null=True)),
                ('cases', models.BigIntegerField(blank=True, null=True)),
                ('cases_day', models.BigIntegerField(blank=True, null=True)),
                ('cases_week', models.BigIntegerField(blank=True, null=True)),
                ('deaths', models.BigIntegerField(blank=True, null=True)),
                ('deaths_day', models.BigIntegerField(blank=True, null=True)),
                ('deaths_week', models.BigIntegerField(blank=True, null=True)),
                ('vac_adm', models.TextField(blank=True, null=True)),
                ('vac_first', models.TextField(blank=True, null=True)),
                ('vac_second', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'State',
                'managed': True,
            },
        ),
    ]
